name: SSH Action Example

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build JAR
        run: ./gradlew build

      - run: ls
      - run: pwd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cicdsample
          path: build

      - name: SSH into remote server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          passphrase: ${{ secrets.REMOTE_SSH_PASSPHRASE }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            mkdir -p ~/cicd
            mkdir -p ~/cccccc111222
            cd ~/cicd || exit
            rm -f *.jar
            ls
            pwd
            # Download the artifact from the GitHub repository
            curl -LJO https://github.com/okanekudasai/githubaction_practice/releases/latest/download/cicdsample.zip
            unzip cicdsample.zip
            rm cicdsample.zip
            # Restart the application or do any necessary deployment steps
      - run: echo "Hello, GitHub Actions!" > hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: hello
          path: hello.txt
      - run: echo "111111111" > hello.txt
      - run: cat hello.txt
      - uses: actions/download-artifact@v3
        with:
          name: hello
      - run: cat hello.txt
            
